[package]
name = "heed-perfs-put-reserved"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.7", features = ["derive"] }
fastrand = "2.0.1"
heed = "0.20.0-alpha.4"
# heed = { path = "../heed/heed" }
roaring = "0.10.2"
serde_json = "1.0.108"
